# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "centos/stream8"

	$server_script = <<-SCRIPT
		systemctl disable firewalld --now
		curl -sfL https://get.k3s.io | K3S_TOKEN_FILE='/vagrant/token' sh -s - --node-ip=192.168.42.110
		sudo chmod 644 /etc/rancher/k3s/k3s.yaml
		sudo yum install -y net-tools
	SCRIPT

	server_name = 'cboulengS'
	config.vm.define server_name do |s|
		s.vm.hostname = server_name
		s.vm.network 'private_network', ip: '192.168.42.110'
		s.vm.provision 'shell', inline: $server_script
  	s.vm.provider "virtualbox" do |vb|
  	  vb.memory = "1024"
  	  vb.cpus = 1
  	end
 	end

	$server_worker_script = <<-SCRIPT
		systemctl disable firewalld --now
		curl -sfL https://get.k3s.io | K3S_URL=https://192.168.42.110:6443 K3S_TOKEN_FILE='/vagrant/token' sh -s - --node-ip=192.168.42.111
		sudo yum install -y net-tools
	SCRIPT

	server_worker_name = 'cboulengSW'
	config.vm.define server_worker_name do |s|
		s.vm.hostname = server_worker_name
		s.vm.network 'private_network', ip: '192.168.42.111'
		s.vm.provision 'shell', inline: $server_worker_script
  	s.vm.provider "virtualbox" do |vb|
  	  vb.memory = "1024"
  	  vb.cpus = 1
  	end
 	end
end
